spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.2.202:3306/LMsg?useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: Frank@668
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: log
logging:
  config: classpath:log4j2.yml

