server:
  port: 8082
  servlet:
    context-path: /
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  profiles:
    active: develop # develop || production
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"